site_name: Malbec Labs
site_url: https://docs.malbeclabs.com/
theme:
  name: material
  logo: logo.png
  faviron: assets/favicon.png
  palette:
    scheme: slate
    primary: grey
    accent: custom
  features:
    - content.code.copy
    - navigation.indexes
    - toc.integrate
    - header.autohide
nav:
  - Welcome: index.md
  - Quick Connect: quick-connect.md
  - Users:
    - Setup: setup.md
    - Tenants:
      - Overview: tenant.md
      - Solana:
        - Validator Mainnet-Beta Connection: DZ Mainnet-beta Connection.md
        - Validator Testnet Connection: DZ Testnet Connection.md
        - Permissioned Connection: Permissioned Connection.md
        - DoubleZero Validator Multicast: ValidatorShredPublishing.md
        - Other Multicast: Multicast Connection.md
        - Paying Fees: paying-fees.md
        - Paying Fees with 2Z: paying-fees2z.md
        - Troubleshooting: troubleshooting.md
      - Shelby:
        - Shelby Connection: Shelby Permissioned Connection.md
      - New Tenant: New Tenant.md
  - Contributors:
    - Overview: contribute-overview.md
    - Requirements & Architecture: contribute.md
    - Device Provisioning: contribute-provisioning.md
    - Operations: contribute-operations.md
  - Architecture: architecture.md
  - Glossary: glossary.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
  - stylesheets/wizard.css
extra_javascript:
  - javascripts/cloudsmith-versions.js
  - javascripts/connection-wizard.js
  - javascripts/page-toolbar.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
