site_name: Malbec Labs
site_url: https://docs.malbeclabs.com/
theme:
  name: material
  logo: logo.png
  faviron: assets/favicon.png
  palette:
    scheme: slate
    primary: grey
    accent: custom
  features:
    - content.code.copy
    - navigation.indexes
    - toc.integrate
    - header.autohide
nav:
  - Welcome: index.md
  - Setup: setup.md
  - Users:
    - Overview: users-overview.md
    - Mainnet-Beta Connection: DZ Mainnet-beta Connection.md
    - Testnet Connection: DZ Testnet Connection.md
    - Mainnet-Beta RPC: DZ Mainnet-beta RPC.md
    - Multicast Mode: connect-multicast.md
    - Paying Fees: paying-fees.md
    - Paying Fees with 2Z: paying-fees2z.md
    - Swapping SOL to 2Z: Swapping-sol-to-2z.md
    - Troubleshooting: troubleshooting.md
  - Contributors:
    - Overview: contribute-overview.md
    - Requirements & Architecture: contribute.md
    - Device Provisioning: contribute-provisioning.md
    - Operations: contribute-operations.md
  - Architecture: architecture.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
