site_name: Malbec Labs
site_url: https://docs.malbeclabs.com/
theme:
  name: material
  logo: logo.png
  faviron: assets/favicon.png
  palette:
    scheme: slate
    primary: grey
    accent: custom
  features:
    - content.code.copy
    - navigation.indexes
    - toc.integrate
    - header.autohide
    - navigation.expand
nav:
  - Welcome: index.md
  - Setup: connect.md
  - Connect - IBRL Mode: connect-ibrl.md
  - Connect - Multicast Mode: connect-multicast.md
  - Contribute: contribute.md
  - FAQs: faqs.md
  - Notices:
    - notices/20250506-testnet-upgrade.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption